spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/h2/datajpa
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true  # ??? ???? ????.
        format_sql: true

        order_inserts: true
        jdbc:
          batch_size: 100
  data:
    web:
      pageable:
        default-page-size: 10
logging.level:
  org.hibernate.SQL: debug  # ??? ???? ????.
# org.hibernate.type: trace